[network_zenoh]
chain_id = '63586a3c0255f337c77a777ff54f0040b8c388da04f23ecee6bfd4953a6512b4'
node_address = '115a0dad56e251986325ee1aadac13dc4c91fc9b'
validator_address = '115a0dad56e251986325ee1aadac13dc4c91fc9b'
grpc_port = 50000
protocol = 'quic'
domain = 'test-chain-node0'
port = 40000
ca_cert = """
-----BEGIN CERTIFICATE-----\r
MIIBbDCCARKgAwIBAgIICcNg/nzG9CUwCgYIKoZIzj0EAwIwITEfMB0GA1UEAwwW\r
cmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80MDk2MDEw\r
MTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDBZMBMG\r
ByqGSM49AgEGCCqGSM49AwEHA0IABALbIShb/NtszvQy9pDVYoBRZM6ZfMdhesD5\r
35oUezZwD3KdCmIBcNUr0qowvL4gqs7Ix7mhRyUEvtSCnsKKarmjMjAwMB0GA1Ud\r
DgQWBBQl9MZ8/mDDCfFWGG+UihItAXG7bjAPBgNVHRMBAf8EBTADAQH/MAoGCCqG\r
SM49BAMCA0gAMEUCIQCBh/NrCyaWZLVKDRMIjZB8dxNUlooksABZtgKuR2LjegIg\r
bqEV4kbcWFbOFo98FtD+C8u1pbiLFvJ3BEkFHsuaIUA=\r
-----END CERTIFICATE-----\r
"""
cert = """
-----BEGIN CERTIFICATE-----\r
MIIBajCCAQ+gAwIBAgIJAPsgp1Weg0YRMAoGCCqGSM49BAMCMCExHzAdBgNVBAMM\r
FnJjZ2VuIHNlbGYgc2lnbmVkIGNlcnQwIBcNNzUwMTAxMDAwMDAwWhgPNDA5NjAx\r
MDEwMDAwMDBaMCExHzAdBgNVBAMMFnJjZ2VuIHNlbGYgc2lnbmVkIGNlcnQwWTAT\r
BgcqhkjOPQIBBggqhkjOPQMBBwNCAAQA9GyaBoUu0iIeaNISBy67BkrtCikA/Jj0\r
qRF92A8wD6OdsSZ4lc0JBDrvfBAbpyKXGRdYM2KNuivIx6ZJT8NEoy4wLDAqBgNV\r
HREEIzAhgh90ZXN0LWNoYWluLXplbm9oLW92ZXJsb3JkLW5vZGUxMAoGCCqGSM49\r
BAMCA0kAMEYCIQDGhOnIqQnL8J9jRbuAFStxB2rWbx8xzi/sXqv/OnCZjQIhAOyb\r
2+70u3BOxjsEK3Wae0sGAMXpHp5LfHyfXEDyBeyq\r
-----END CERTIFICATE-----\r
"""
priv_key = """
-----BEGIN PRIVATE KEY-----\r
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgfaJUURu+pnbfMBRT\r
ARMA/Dra4BsmKKSS9pwdzeed8vKhRANCAAQA9GyaBoUu0iIeaNISBy67BkrtCikA\r
/Jj0qRF92A8wD6OdsSZ4lc0JBDrvfBAbpyKXGRdYM2KNuivIx6ZJT8NE\r
-----END PRIVATE KEY-----\r
"""

[[network_zenoh.peers]]
domain = 'test-chain-node1'
protocol = 'quic'
port = 40001

[[network_zenoh.peers]]
domain = 'test-chain-node2'
protocol = 'quic'
port = 40002

[[network_zenoh.peers]]
domain = 'test-chain-node3'
protocol = 'quic'
port = 40003
