[network_zenoh]
chain_id = '63586a3c0255f337c77a777ff54f0040b8c388da04f23ecee6bfd4953a6512b4'
node_address = '115a0dad56e251986325ee1aadac13dc4c91fc9b'
validator_address = '115a0dad56e251986325ee1aadac13dc4c91fc9b'
grpc_port = 50000
protocol = 'tls'
domain = 'peer0'
port = 40000
ca_cert = 'cert/ca_cert.pem'
cert = 'cert/peer0/cert.pem'
priv_key = 'cert/peer0/key.pem'

[[network_zenoh.peers]]
domain = 'peer1'
protocol = 'tls'
port = 40001

[[network_zenoh.peers]]
domain = 'peer2'
protocol = 'tls'
port = 40002

[[network_zenoh.peers]]
domain = 'peer3'
protocol = 'tls'
port = 40003
