[package]
name = "network"
version = "6.6.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
edition = "2021"

[dependencies]
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git" }
flume = "0.10"
tokio = { version = "1", features = ["rt-multi-thread", "time"] }
tokio-util = "0.7"
parking_lot = "0.12"
toml = "0.5"
serde = { version = "1", features = ["derive"] }
bytes = "1"
hex = "0.4"
thiserror =  "1"
tentacle-multiaddr = "0.3"
clap = { version = "3.1", features = ["derive"] }
backtrace = "0.3"
log = "0.4"
log4rs = { version = "1.1", features = ["gzip"] }
md5 = "0.7"
json5 = "0.4"

tonic = "0.5"
prost = "0.8"

cloud-util = { git = "https://github.com/cita-cloud/cloud-util.git" }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto.git" }
status_code = { package = "cloud-code", git = "https://github.com/cita-cloud/status_code.git" }
